services:
  gitlab:
    image: gitlab/gitlab-ce:16.5.3-ce.0 
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - '${GITLAB_BACKUP_DIR}:/mnt/gitlab/backups'
      - '${GITLAB_RESTORE_DIR}:/mnt/gitlab/restores'
      - '${GITLAB_INIT_TASK_DIR}:/init_tasks'
      - "${GITLAB_CROND_DIR}/${GITLAB_BACKUP_CRON}:/etc/cron.d/${GITLAB_BACKUP_CRON}"
      - "${GITLAB_CRON_TASKS_DIR}:/etc/cron_tasks"
    shm_size: '256m'
    mem_limit: '4g'
    memswap_limit: '4g'
    cpus: '4'
    pids_limit: '600'
    command: bash -c "for task in /init_tasks/*;do $$task ; done ; /assets/wrapper"