#!/bin/bash

source /env/gitlab_env

gitlab_restore_dir=/mnt/gitlab/restores
gitlab_config_dir=/etc/gitlab

gitlab_rb=gitlab.rb
gitlab_secrets=gitlab-secrets.json

# 文件删了才能够恢复备份
gitlab_tag=restored

suffix_pattern="_gitlab_backup.tar"


restore_func() {
    if [ "${GITLAB_RESTORE_INIT}"x == "1"x -a ! -f ${gitlab_restore_dir}/${gitlab_tag} ]; then
        gitlab_back=$(echo $GITLAB_RESTORE_FILE | awk -F${suffix_pattern} '{print $1}')
        echo "Restoring GitLab backup: ${gitlab_back}${suffix_pattern}"

        rsync -ahW --progress --partial ${gitlab_backup_dump_dir}/${gitlab_back}${suffix_pattern} ${gitlab_backup_dir}/ && \
        gitlab-backup restore BACKUP=${gitlab_back} force=yes && \
        rsync -ahW --progress --partial ${gitlab_backup_dump_dir}/${gitlab_back}_${gitlab_rb} ${gitlab_config_dir}/${gitlab_rb} && \
        rsync -ahW --progress --partial ${gitlab_backup_dump_dir}/${gitlab_back}_${gitlab_secrets} ${gitlab_config_dir}/${gitlab_secrets} && \
        touch ${gitlab_restore_dir}/${gitlab_tag}
    fi
}


if [ -z "$1" ]; then
    restore_func
else
    case $1 in
        restore) 
            restore_func
            gitlab-ctl reconfigure && gitlab-ctl restart
            break
            ;;
        **)
            echo "Usage: $0 [restore]"
            break
            ;;
    esac
fi

