#!/bin/bash

gitlab_backup_dir=/var/opt/gitlab/backups
gitlab_backup_dump_dir=/mnt/gitlab/backups

rm -fr ${gitlab_backup_dir}

cp -r ${gitlab_backup_dump_dir} ${gitlab_backup_dir}

chown -R git:git ${gitlab_backup_dir}
